// Routes included in sitemap.xml (keep in sync with App.tsx routes).
export const SITEMAP_PATHS = [
  '/',
  '/blog',
  '/blog/nezavazne-seznamovani-pro-studenty',
  '/blog/sexualni-vychova-co-studenti-potrebuji-vedet',
  '/blog/souhlas-a-hranice-zaklad-bezpecneho-seznamovani',
  '/privacy',
  '/terms',
  '/community-guidelines',
  '/account-deletion',
  '/support',
  '/child-safety',
  '/moderation',
  '/security',
  '/cookies',
  '/en/privacy',
  '/en/terms',
  '/en/community-guidelines',
  '/en/account-deletion',
  '/en/support',
  '/en/child-safety',
  '/en/moderation',
  '/en/security',
  '/en/cookies',
] as const;
